"""upload and download pdf reports

Revision ID: f77ae8b8fb02
Revises: c89ad873e46a
Create Date: 2024-03-07 09:42:03.512817

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
import os
from flask import current_app


# revision identifiers, used by Alembic.
revision = 'f77ae8b8fb02'
down_revision = 'c89ad873e46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('grade', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint([teacher_id], [Teacher.id]),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Student')
    # ### end Alembic commands ###
